### ISSUE TITLE
Adapt for docker compose

### ISSUE THREAD

**Issue by pvieira84** [agusalex/ghostfolio-sync#18]
I'm trying to create this container with docker compose but not succeeding because we it needs the bearer token as an env variable. Would it be possible to supply the ghostfolio user key instead and the script would then fetch the bearer token?

**Comment by agusalex** [comment]
Sorry for the delay, why would passing env variable to docker run a container be different from when run in docker-compose?
On the bearer token side of things, never tested it but certainly possible. Feel free to draft a PR for this and I can review it!

**Comment by agusalex** [comment]
Thanks for adding this! we can now close it as done!
